version: '3.8'

networks:
  momolo-2-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - momolo-2-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy      
    env_file:
      - ./backend/.env.production
    networks:
      - momolo-2-network
    restart: unless-stopped

  db:
    image: postgres:16.9
    networks:
      - momolo-2-network
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}           
      POSTGRES_PASSWORD: ${DB_PASSWORD}   
      POSTGRES_DB: ${DB_DATABASE}         
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.27.5-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - momolo-2-network
    restart: unless-stopped
  certbot:
    image: certbot/certbot:v4.0.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - momolo-2-network
    entrypoint: ""
    command:
      - certbot
      - certonly
      - --webroot
      - --webroot-path=/var/www/certbot
      - --email
      - nguyenchin0077@gmail.com
      - --agree-tos
      - --no-eff-email
      - --non-interactive
      - --expand  
      - -d
      - momolo.io.vn
      - -d
      - www.momolo.io.vn
      - -d
      - api.momolo.io.vn   


volumes:
  postgres_data:
